### ISSUE TITLE
Empfohlenes "Mutter"-AddOn für Settings

### ISSUE THREAD

**Issue by polarpixel** [redaxo/redaxo4#247]
Ich glaube, es wurde schon mal diskutiert, aber nichts beschlossen, wenn ich mich erinnere:
Ich fände es sehr begrüßenswert, wenn es eine vom Core-Team empfohlene Lösung gibt, um z.B. Backend-Settings zu verwalten. Aktuell würde ich in meinem Backend-Theme gern einige Optionen anbieten und würde mich über eine allgemein anerkannte Basis freuen.
Klar: Ich kann einen eigenen Menüpunkt aufmachen oder Rudis be_utilities nutzen.
Wäre es aber nicht besser, wenn es da eine Vorgabe gäbe, einen optional aktivierbaren be_style-Menüpunkt z.B., an den man dann ran könnte?

**Comment by dergel** [comment]
da für r5 geplant und r4 nicht in die planung passt, schliesse ich das mal.. Müsst also bei den AddOns bleiben
