### ISSUE TITLE
Ideen zu einem zukünftigen Image-Manager

### ISSUE THREAD

**Issue by summsel** [redaxo/redaxo4#249]
Video und Bild sind in den letzten Jahren auch für CMS-User immer zentraler geworden; ich manchen Anwendungsbereichen sogar zentraler als Text. 

Trotzdem sind CMS häufig noch auf Text als zentrale Inhalte ausgerichtet. Bilder und Videos auf dem Desktop fürs CMS bereitzustellen, überfordert den CMS-User schnell: Software fehlt und überfordert, KnowHow über dpi, Formate, Dateigrösse, Relevanz für Suchmaschinen, geschweige denn Responsiveness sind nicht vorhanden. Der User lädt das Bild hoch, aus den Augen, aus dem Sinn. Von einer solchen Anwendung aus gesehen, macht ein zentrales Image Addon sehr Sinn und könnte folgende Funktionen zur Verfügung stellen:

1 - bequemer Massen-Upload a la Drag and Drop (momentan "Multiupload")
2 - Bildgrössen-Begrenzung beim Upload (momentan "decaf_upload_precrompessor")
3 - Optimierung des Bildes (Entfernen Farbprofile, Kommentare etc.) (IMG Optimizer, Artikel dazu hier)
4 - Ablage des Bildes, so dass es wieder gefunden wird (Titel, Kategorien, momentan „Medienpool“)
5 - Zuschneidung des Bilders (momentan "Image-Cropper")
6 - Filter, Wasserzeichen etc. (momentan „Image Manager)
7 - Verkleinerung a la Resizer (momentan „Image Resize“ und „Image Manager“
8 - Responsiveness
- - angepassten Ausschnitt je nach Medium anzeigen 
- - angepasste Dateigrösse ausgeben (da gibts auch ein Addon "Responsive Images")
9 - SEO: geschickte, beschreibende Dateinamen (momentan manuel auf Desktop)

Im SEO-Bereich geschieht sehr interessantes mit den Addons SEO42 und Resource-Includer, die .htaccess wird ebenfalls beachtet, zipping und cache kommen dazu. Spped wird ein wichtiger Faktor im SEO und so landet man wieder bei der Bild-Optimierung, die dann am besten gleich als CMS-Automatisierung geschieht beim Upload. Auch der Bereich Responsiveness schreit nach Automatisierung.

An und für sich ein Riesen-Feld... aber ein zentrales Addon "Image-manager" mit Plugins könnte in Zukunft ein Core-Feature und Entscheidungs-Kriterium für Redaxo sein. Alles einstellen, Files raufladen, fertig: Website ist ready für Google und Mobile.:) 

Ich wünschte ich hätte etwas mehr Mittel und würde das dann gleich finanzieren :) Bei Spendenaufrufen wie damals fürs Community-Addon wär ich gleich dabei.

Ist mir natürlich klar, dass ihr nicht alles machen könnt und solltet und Open Source kein Bedienladen ist.

Dies also einfach als Sharing von einer wenigstens für mich interessanten Perspektive.

Bereits bestehende Open Source Lösungen, die vielleicht als Plugins eingebaut werden könnten:

Image Optimizer Open Source Code: 
- http://www.smashingmagazine.com/2013/12/17/imageoptim-cli-batch-compression-tool
- http://imageoptim.com/
Responsive Image Thematik (Bildgrösse, nicht Ausschnitt) via php (perfekt für Image Manager :) gelöst: 
- http://adaptive-images.com/

Kai

**Comment by dergel** [comment]
übernehme das in redaxo5 als ideen.. in r4 wird das wohl erstmal nichts..
