### ISSUE TITLE
convert2img

### ISSUE THREAD

**Issue by skerbis** [redaxo/redaxo4#258]
Es wäre toll, wenn man das Plugin für die Miniaturdarstellung im Medianpool deaktivieren könnte. Gerade bei langen Dateilisten mit PDF scheint es zu einem Speicherüberlauf beim Webserver zu kommen. 
Eine andere Alternative wäre die Wiedereinführung des Lazy Loadings für die Bilder.

**Comment by shauste** [comment]
Leider greift dieser Efffekt in Redaxo 4.6.1 nicht, ERROR erscheint. Gibt es Voraussetzungen an den Server, damit die Umwandlung korrekt erfolgt?

**Comment by olien** [comment]
Habe gerade das gleiche Problem bei 1und1. Bei DF funktioniert das auf zwei Seiten problemlos....
(REX 4.6.1)

**Comment by staabm** [comment]
convert2img erfordert dass man `exec` aufrufen darf, was bei shared hostern oft nicht der fall ist:

https://github.com/redaxo/redaxo4/blob/master/redaxo/include/addons/image_manager/classes/effects/class.rex_effect_convert2img.inc.php#L41

**Comment by olien** [comment]
Danke für die Info. (Der Hinweis wär cool!)

**Comment by skerbis** [comment]
Hinweis: einige Anbieter unterstützen evtl. system ... das Skript könnte ja beide (exec oder system) checken.
