### ISSUE TITLE
Nette 2. Demo erwünscht.. 

### ISSUE THREAD

**Issue by dergel** [redaxo/redaxo4#260]
Jemand da, der eine 2. Demo für REDAXO erstellen will. Ich stell mir was sehr standardmäßiges vor - eventuell bootstrap. Soll dann als Basis für einige User dienen, die das dann adaptieren können.

Jemand zeit und Interesse. In die Demo soll dann natürlich auch der Firmenname des Erstellers (falls das jemanden motivieren) ..

lg

**Comment by gupi** [comment]
Gibt es hier was neues?
Mich wurde eine bootstrap  demo auch sehr interessieren, das ich dies gerne für das training meiner Söhne ( Studenten ) nutzen würde. Ich führe die gerade an Redaxo heran.
da ich Xform liebe, veruche ich mich gerade an einer Anpassung an Bootstrap.
Gunter

**Comment by polarpixel** [comment]
Ich bin an meiner Demo leider noch nicht nennenswert weiter gekommen. Es wird Dich aber sicher freuen zu hören, dass es in der aktuellen Version von Xform ein Bootstrap-Theme gibt, das im Wesentlichen das benötigte Markup ausliefert.

**Comment by skerbis** [comment]
Hallo Peter, 

sorry, dass ich mich so lange nicht mehr gemeldet habe. 
Auch ich konnte kaum an einer Demo arbeiten. Es liegt zum Teil an mir und der aktuellen guten Auftragslage. 

Aber leider auch ein wenig an Redaxo selbst. 

Es ist schwierig Module für aktuell beliebte Designs zu entwickeln. 
Ich brauche irgendwie eine Lösung Blöcke leicht in einander verschachteln zu können. 

Beispiel: 
Man wählt einen 3 Spalten-Block und kann dann in die jeweilige Spalte wieder Blocks einsetzen. 
Redaxo ist zu eindimensional in der Contentpflege. Für Wordpress gibt es bereits solche Lösungen. Es ist so sehr einfach eine Seite zu layouten. 
Etwas in dieser Art evtl.: http://www.elegantthemes.com/gallery/elegant-builder/
Das Blockprinzip von Redaxo war ein guter Anfang muss aber weiterentwickelt werden. Das kann ich aber nicht. 

Es muss also mehr Layoutmöglichkeiten geben für aktuelle responsive Designs.
Ein Theme alleine reicht also nicht wirklich. Die Zuordnung von Blöcken muss sich ändern. 

Man kann eine Demo mit statischen Templates bauen, was aber am Ende nur Frust bei den Nutzern verursacht.

**Comment by polarpixel** [comment]
Das heißt, dass Du dann doch keine Demo machst oder keine Bootstrap-Demo?

Wir diskutieren solche Lösungen ja auch schon lange, auch z.B, verschachtelte Module, aber da gibt es derzeit keine Pläne.

Ich muss gestehen, ich selbst habe das nur selten als Manko empfunden, da ich z.B. verschachtelte Spalten und Subspalten auch als zu komplex für den Redakteur empfinde. Ich denke, man kann in einem Modul die Wahl lassen, ob er 1, 2, 3 oder von mir aus auch vier Spalten zur Verfügung bekommt und dann entsprechend darauf reagieren. Ich bin der Meinung, Module sollten auch nicht zu komplex und zu mächtig werden für den Redakteur, sondern eher für den jeweiligen Zweck maßgeschneidert.

**Comment by gupi** [comment]
Ich habe mal die Ergebnisse unserer aktuellen Trainings-Session zu Redaxo und Bootstrap zusammengefasst. Ist zwar noch nicht fertig aber zeigt möglicherweise einen Weg zu einer Redax-Bootstrap Demo: http://demo.idmerkmal.de
Kommentare erwünscht!

**Comment by polarpixel** [comment]
Na, da bin ich ja mal gespannt, wie das im Backend gelöst ist. Freue mich darauf, das zu sehen. Danke!

**Comment by skerbis** [comment]
Dem Schließ ich mich voll und ganz an. Bin sehr interessiert.

**Comment by olien** [comment]
Hi,

vielleicht könntest Du mal einen eingeschränkten Backend Zugang einrichten???

LG
Oliver

**Comment by gupi** [comment]
Hallo Allerseits,
Ich habe die Bootstrap relevanten Module in den How-to's angezeigt.
Den Backend-Zugang will ich gerne einrichten, weiss aber nicht wie ich die Rechte so einstelle, dass ein Redakteur mehr als nur die Inhalte der Artikel sehen bzw. ändern kann.
Hier der eingeschränkte Zugang: knecht/knecht
Ich stelle gerne einen Admin Zugang zur Verfügung möchte aber die credentials nicht hier veröffentlichen, aber gerne per Mail oder pm im REDAXO Forum.

**Comment by olien** [comment]
Hallo,

danke für den Zugang. So richtig habe ich jetzt dadurch allerdings nicht verstanden wie die Inhalte gepflegt werden...

LG
Oliver

**Comment by polarpixel** [comment]
Geht mir ähnlich. Hab mich nicht allzu lange drin vertieft, aber das Prinzip erschließt sich mir noch nicht automatisch, und ich sehe auch noch nicht Weg mit dem Drag&Drop-Panel.
Kannst Du uns noch ein paar Hinweise geben?

**Comment by gupi** [comment]
Drag and drop ist auch noch in der Entwicklung, deshalb habe ich ja auch noch den workaround aktiv.
Die inhalte hole ich derzeit aus den meta infos der bilder titel, beschreibung ...

**Comment by darwin26** [comment]
ich häng mich da mal rein ... hab da mal was erstellt ...
http://www.redaxo.org/de/forum/webseiten-kommentare-f7/rexponsive-redaxo-als-responsive-demo-t20556.html

**Comment by dergel** [comment]
eine bootstrap demo haben wir nun .. innerhalb von r4 brauchen wir keine demo mehr .. r5 demo mit community ist in arbeit
