### ISSUE TITLE
mpool media page: cat wechsel ohne page reload..

### ISSUE THREAD

**Issue by jdlx** [redaxo/redaxo4#274]
.. erspart ständige page reloads, d.h. macht das Arbeiten mit dem mpool deutlich geschmeidiger. Technisch wie folgt einfach lösbar:

* media page gibt grundsätzliche _alle_ files in der table aus, aber:
 * die `tr` sind erstmal alle ausgeblendet, haben die mcat_id als CSS Klassennamen
 * die `img` haben als `src` ein generisches loading img (oder wahlweise ihr mime icon) und die tatsächliche src in einem `data-src` attr
* onload werden anhand der mcat_id der cat select die korrespondierenden `tr` sichtbar gemacht und das `src` vom generischen img auf das tatsächliche aus `data-src` gesetzt
* on cat select change:
 * ein/ausblenden der `tr`, setzen der `src` attrs
 * callback um die aktuelle mcat in SESSION zu schreiben..

**Comment by dergel** [comment]
damit muss man leider leben. nehmen wir aber als anregung in r5 mit
