### ISSUE TITLE
Sicherstellen dass JPEG Bilder via ImageManager nach umwandlung immer progressiv/interlaced sind

### ISSUE THREAD

**Issue by staabm** [redaxo/redaxo4#281]
de2.php.net/ImageInterlace

**Comment by mayospacken** [comment]
Gibt es inzwischen einen Filter / Effekt / whatever? Ich Nutze Redaxo 4.6.1 und konnte weder im Backend noch in einer Suchmaschine ein zufriedenstellendes Ergebnis finden. Mir z.B. ist baseline jpg ein Dorn im Auge, weil der Nutzer bei großen Datenmengen weniger Feedback als bei progressive jpg bekommt.

**Comment by gharlan** [comment]
Im Medien Manager in R5 ist es drin.
