### ISSUE TITLE
Artikel Online/Offline - 3. status "hidden" o.ä. ...

### ISSUE THREAD

**Issue by jdlx** [redaxo/redaxo4#300]
.. weil es gerade mal wieder im chat aufkam:

Es gibt lediglich die beiden Status `online` & `offline` .. damit gibt es diverse Probleme:
- Anfänger verstehen die technische Bedeutung nicht.. 
  - weder den üblichen Kontext "in Navigation (un)sichtbar"
  - noch den Umstand das offline eben **nicht** bedeutet das der Artikel nicht aufgerufen werden kann..
- es gibt Anforderungen wo man Artikel braucht die im üblichen Sinne offline sind - sprich nicht in der Navi, aber aufrufbar - und parallel Artikel die explizit nicht aufrufbar sein sollen.. zumindest nicht ohne spezifische Konditionen (Admin z.b.)

D.h.: es gibt hier einerseits ein Problem mit mißverständlicher Terminologie, und eines dahingehend, daß es nur 2 Status gibt.. wo 3 - aka hidden o.ä. - nötig wären.

_ps.: ja, man kann das über Umwege lösen.. metainfo o.ä., aber das ist nicht der Punkt.._

**Comment by svenhaile** [comment]
Weshalb bedeutet 'offline' eigentlich 'online' bei Redaxo?

Das Geschaeft meines Kollegen hat den Kontakt verloren mit ihrem Webdesigner. Nun editiere ich zum ersten Mal eine Webseite mit Redaxo-Verwaltung. Die 'offline' gesetzten Seiten sind noch online erreichbar! Seit 2001 programmiere ich CMS und habe erwartet, dass offline wirklich unerreichbar bedeutet fuer die Aussenwelt. Schliesslich kann ich keine Option 'Inaktiv' finden. 

Ich kann nicht an nicht an den Server heran, also keine Add-ons oder Systemlevel-Konfigurationen betaetigen. Gibt es eine Loesung auf Userlevel? Wenn nicht, dann wird die Seite natuerlich sofort transferiert werden muessen auf ein anderes System. Auch wenn die Redaxo CMS die Editierung der einzelnen Seiten sehr einfach macht, es macht keinen Sinn, dass die Users Seiten loeschen muessen, welche noch in Ueberarbeitung sind, um zu verhindern dass diese zwischenzeitlich von Drittparteien aufgegriffen werden koennen. Bitte um Ratschlag. Danke!

**Comment by IngoWinter** [comment]
Sofort transferieren. Bitte.

**Comment by skerbis** [comment]
Für die Umsetzung der online/offline „Option“ ist der Entwickler der Website verantwortlich. Sofern rex_navigation verwendet wird, werden die Seiten „nur“ ausgeblendet. Eine Sperrung der Seiten ist durch ein kurzes Codeschnipsel in den Templates möglich.  Was heißt du kommst nicht an den Server ran?

**Comment by AWqxKAWERbXo** [comment]
Ich finde die Antworten nicht gerade lösungsorientiert.

In REDAXO 5 gibt es das Addon `access_denied`, welches genau diese Funktionalität umsetzt und einen weiteren Status "gesperrt" hinzufügt, der genau das umsetzt. Für REDAXO 4 gibt es ebenfalls ein Addon. 

Background: Es gab immer wieder Diskussionen dazu und ich finde es auch unbefriedigend, den Status "offline" zu nennen, aber erreichbar zu lassen. Historisch gesehen war das je nach Kontext auch praktisch, Artikel aufrufbar - aber nicht in der Navigation o.ä. zu halten. Leider wird, zurecht, der Begriff "offline" oft missverstanden.

**Comment by IngoWinter** [comment]
> Ich finde die Antworten nicht gerade lösungsorientiert

Er schreibt er könne keine Addons installieren. Dein Hinweis, dass es ein passenden Addon gibt, ist also auch nicht wirklich lösungsorientiert :)

Ausserdem schreibt er, er könne "sofort" auf ein anderes CMS umstellen - von daher ist das dann wohl die beste Lösung (speziell weil er keine Ahnung von Redaxo hat).

**Comment by AWqxKAWERbXo** [comment]
Kann ja sein, dass ein Update infrage kommt oder man dann doch gewillt ist, an das System ranzukommen, wenn man die Funktion so einfach nachrüsten kann. Bis hin zu Anpassungen im Template, wenn man zumindest da rankommt oder Benutzerrechte-Hijacking, wenn der ursprüngliche Entwickler nachlässig war. Alles denkbar.
