### ISSUE TITLE
Setup Schritt 3: Radio Button " REDAXO 4.6 Export einspielen [Demo einspielen]" taucht nicht auf.

### ISSUE THREAD

**Issue by RexDude** [redaxo/redaxo4#345]
Geht man dann einen Schritt vor und wieder zurück taucht es plötzlich wieder auf. 

EDIT: Wurde auch im Forum neulich angesprochen von einem REDAXO Neuling.

**Comment by dergel** [comment]
hmm.. wohl auch ein altes Problem .. Kann ich nicht nachvollziehen...
