### ISSUE TITLE
OOAddOn innerhalb eines Plugin-Install

### ISSUE THREAD

**Issue by Hirbod** [redaxo/redaxo4#347]
Hi,

ggf. mal überlegt das doch noch für R4 zu verbessern?
http://www.redaxo.org/de/forum/addons-f30/merkwurdiges-verhalten-ooaddon-isavailable-t17568.html

Ich würde das für sinnvoll halten!

**Comment by dergel** [comment]
bei R4 leider nicht mehr .. Zu tiefe Eingriffe
