### ISSUE TITLE
ImageManager - Convert2Img PHP 5.3.x

### ISSUE THREAD

**Issue by skerbis** [redaxo/redaxo4#348]
Convert2Img - Filter funktioniert nicht. 
PHP 5.3.x, PLESK, SUSE 12.3 -  ImageMagick ist installiert. 
Das alte "Plugin" bevor es ein Filter wurde, funktioniert.

**Comment by dergel** [comment]
ich glaube (aber beleere mich eines besseren), dass die beiden beispiele auf verschiedenen servern laufen. eins vielleicht sogar lokal auf mac osx ? .. so bei mir.. und hier gibt es kein "convert", so dass die umwandlung auf dieser ebene nicht geht.. Ich schliesse das hier - aber melde dich wenn ich falsch liege.

**Comment by skerbis** [comment]
Sorry, hat sich längst erledigt. Auf allen Servern läuft ein aktuelles 5.6.x, da funktioniert es. OS X war hier aber nicht beteiligt. Alles Vserver mit Debian oder Ubuntu.
