### ISSUE TITLE
Medium wird gelöscht obwohl in AddOns noch vorhanden

### ISSUE THREAD

**Issue by tbaddade** [redaxo/redaxo4#351]
> Das Problem: möchte eine Datei im Medienpool löschen, wird nur kontrolliert ob diese in einem Artikel verwendet wird. Wird eine Datei ausschließlich in einem Addon verwendet, erfolgt keine Warnung, sondern die Datei wird einfach gelöscht.

Wie können wir das für AddOns besser, einfacher anbieten?

Kann die rex_form Klasse die Felder vorhalten?

EP `OOMEDIA_IS_IN_USE` ist vorhanden.

siehe auch http://www.redaxo.org/de/forum/post112413.html

**Comment by dergel** [comment]
so ein array wäre ziemlich gross, ist dann nicht eventbezogen und sicherlich bald überladen... deswegen hier erstmal nicht mehr.
