### ISSUE TITLE
Update 4.2.* auf 4.6 -> rex_679_types fehlerhaft

### ISSUE THREAD

**Issue by Sysix** [redaxo/redaxo4#352]
Hallo Leute!

mir ist das jetzt schon öfters aufgefallen. Wenn ich ein Redaxo Update mache (4.6.1 aufsetzen, installieren, setup neu starten, importieren) dann funzt der imagemanger nicht gescheit, sprich er haut mir fehler raus. Ich hab schon frisches redaxo runtergeladen und versucht ohne Fehler zu updaten. Fehler bleibt weiterhin bestehen.
Das einzige was ich machen kann, ist das Addon einfach zu re-installieren. Dann klappts auch :)
Aber ich glaub das ist nicht, der Sinn der Sache oder?

Gruß Sysix

**Comment by dergel** [comment]
ist wohl nicht mehr so.. wenn ja, bitte mit fehlermeldung neu posten
