### ISSUE TITLE
xform und community nicht als submodule einbinden

### ISSUE THREAD

**Issue by IngoWinter** [redaxo/redaxo4#356]
ich würde weder xform noch community als submodule einbinden. gerade in letzter zeit hats bei beiden addons häufigst korrekturen gegeben, für die jedes mal das submodule hätte aktualisiert werden müssen. das ist ne mühsame geschicht, deswegen sollten imho beide addons entweder im core dateibestand drin sein oder gar nicht - auch nicht per submodule.

vor einiger zeit bin ich genau über die geschichte gestolpert. fehlerhaftes xform über submodule gezogen, obwohl der fehler im im xform repo schon länger gefixt war. und zumindest das xform submodule hängt gerade schon wieder derbe hinterher, com hab ich nicht geguckt.

**Comment by dergel** [comment]
lassen wir hier noch so drin.. kommt die tage sowieso noch ein update. der installer erlaubt dann auch addonupdates.. mittlerweile deswegen nicht mehr so relevant
