### ISSUE TITLE
$REX[*VERSION] … vernünftige Konvention bitte …

### ISSUE THREAD

**Issue by jdlx** [redaxo/redaxo4#367]
… ist aktuell ziemlich für die Katz.. mit allein `dev` als `MINORVERSION` hat man keine Ahnung mit welcher (Minor)Version-Basis man es zu tun hat..

**Comment by dergel** [comment]
>Nach jeder tag Version (aka Release) wird die MiinorVersion pauschal um +1 hochgesetzt und -dev 

das sollten wir genauso machen..
