### ISSUE TITLE
Image Manager :: Effekt "workspace"

### ISSUE THREAD

**Issue by matthiasphilipp** [redaxo/redaxo4#382]
Effekt "workspace" Im Zusammenspiel mit Effekt "resize" u/od "crop" wird kein Bild erzeugt
Image Manager: 1.2 / 1.2.1
Redaxo: 4.6.1
PHP: 5.4.3

**Comment by dergel** [comment]
was passiert ? Errorbild oder ein Fehler ? Kannst Du die Fehlermeldung aktivieren und ausgeben lassen und dann das "kaputte BIld" als Textdatei ansehen und die Fehler durchschicken ? lg

**Comment by dergel** [comment]
war ein fehler in den Bildformatbezeichnungen.. passiert bei png/gif mit transparenz und workspace effekt.. ist behoben hier in der github version.

**Comment by tbaddade** [comment]
> ist behoben hier in der github version.

https://github.com/redaxo/redaxo4/commit/1992dfc8f1db322ebc81a82d767f3fe37ff64e02

**Comment by matthiasphilipp** [comment]
Danke schön.
