### ISSUE TITLE
Metadaten für Medienkategorien 

### ISSUE THREAD

**Issue by DanielWeitenauer** [redaxo/redaxo4#383]
Es wäre sehr praktisch, wenn man für die Medienkategorien über das Metainfo Addon eigene Metadaten anlegen könnte, z.B. um übersetzbare Katalog-Überschriften für das Frontend erstellen zu können.

**Comment by tbaddade** [comment]
Du könntest dieses AddOn[1] verwenden und deine Kategorien so ausgeben

`{{ Medienpoolkategoriename }}`

Im Addon trägst du dann `Medienpoolkategoriename` ein und kannst dies dann frei übersetzen lassen.

[1] https://github.com/tbaddade/rex_opf_lang

**Comment by DanielWeitenauer** [comment]
Danke für Deinen Vorschlag. So mache ich es im Moment, das ist auf Dauer allerdings etwas umständlich.
Ist im Prinzip auch nur ein ausgesuchtes Beispiel. Ich hatte auch schon das Problem, dass ich zusätzliche Infos zu den Kategorien speichern musste, um sie für bestimmte Ausgaben filtern oder sortieren zu können. Daher fände ich es auf Dauer nicht schlecht, wenn es eine Möglichkeit gäbe, die Medienkategorien wie die Artikelkategorien beliebig mit Infos zu erweitern.

**Comment by DanielWeitenauer** [comment]
Ich räume meine Issues auf und schließe hier, weil es inzwischen Version 5 gibt.
