### ISSUE TITLE
Installer Addon: Nicht die neuste Version runtergeladen

### ISSUE THREAD

**Issue by Sysix** [redaxo/redaxo4#385]
Hallo Leutz,

ich hab heut via den Installer das xform AddOn runtergeladen und jetzt bemerke ich, dass er mir nicht die neuste Version gegeben hat.

Beim herunterladen, war die neuste Version die 4.9 und nun sagt er es gibt ein Update auf 4.12.
An sich ja kein Thema, ist ja aber nicht das Ziel :)

Liegt es daran, dass es vielleicht als String geschaut wird? Da kommt die 9 vor die 1(2)

Gruß Sysix

**Comment by gharlan** [comment]
Beim Check, ob eine Version neuer ist, wird nicht nach den Strings geschaut, daher taucht die 4.12 schon auf.
Aber die Sortierung aller verfügbaren Versionen ist falsch, demnach steht die Version 4.12 unten, und die 4.9 oben. (Da greift in der Tat das Problem, dass der String "12" kleiner ist als "9").

![bildschirmfoto 2015-02-23 um 21 48 18](https://cloud.githubusercontent.com/assets/330436/6336811/a52e9680-bba5-11e4-801b-9d32ec06445a.png)

Die gleiche Reihenfolge der Versionen hier wird dann auch in der Detailsicht verwendet, also 4.12 unten..

**Comment by skerbis** [comment]
Macht doch auch keinen Sinn dass eine Version 4.12 neuer sein soll als eine Version 4.9 ... Nach 4.9 kommt 4.91, 4.92, 49x.xx und dann eben 5.  Eine 4.10 wäre doch identisch mit 4.1

**Comment by gharlan** [comment]
Die Interpretation ist meiner Meinung nach unüblich. `4.1` ist gleich `4.1.0` aber nicht `4.10`.
Beispiel OS X: nach `10.9` (Mavericks) kam `10.10` (Yosemite). Und jeweils gibt es dann noch Unterversionen (z. B. `10.10.2`).

Siehe auch http://semver.org (halten sich viele dran). Auch dort steht:

> 1.9.0 -> 1.10.0 -> 1.11.0

**Comment by skerbis** [comment]
Hast Recht. 
Deshalb habe ich den Post gelöscht.

**Comment by gharlan** [comment]
Die Versionen werden nun korrekt sortiert (und direkt so ausgeliefert von der Api).
