### ISSUE TITLE
Medienpool: differenziertere Benutzer-Rechte

### ISSUE THREAD

**Issue by mbodon** [redaxo/redaxo4#386]
Ich würde mir wünschen das ich einem Benutzer die Rechte entziehen kann für "Medium hinzufügen" (da ich meistens Multiupload noch zusätzlich verwende) und auch "Dateien synchronisieren" (jedesmal werde ich bei der Redaxo-Schulung gefragt was der Menüpunkt macht und wie man Bilder per FTP hochlädt ... dieses Feature braucht Tante Liselotte wirklich nicht ;-) 

Alles Wünsche, keine Bugs !

**Comment by skerbis** [comment]
Ja, Medium hinzufügen könnte besser durch einen neuen Multiupload-fähigen Dialog ersetzt werden. Dateien synchronisieren wäre auch eher was für Admins.

**Comment by dergel** [comment]
Medium hinzufügen lassen wir vorerst so.. in r5 gerne nochmal überlegen -> issue setzen.. Dateien sync und auch Kategorien bearbeiten ist dann doch eher Adminsache
