### ISSUE TITLE
.redaxo Dateien fehlen

### ISSUE THREAD

**Issue by RexDude** [redaxo/redaxo4#387]
http://www.redaxo.org/de/forum/installation-f26/wo-soll-bei-linux-datei-redaxo-stehen-t20346.html

Kommt immer wieder mal vor dass diese Dateien per FTP nicht übetragen werden. Ist zum Beispiel die default Einstellung von FireFTP (für Firefox).

Evtl. wäre es gut die Ordner zu prüfen ob die da sind und nicht diese "unsichbaren" Dateien.

**Comment by dergel** [comment]
eigentlich könnte man die .redaxo einfach in redaxo dateien ändern. (ohne Punkt) . in files wäre es zwar eine Datei die beim Sync auftaucht, aber dann sollte es mit ftp und unzip etc keine Probleme geben.. hmm

**Comment by RexDude** [comment]
Find ich nicht so sauber. Früher hiessen die ja _irgendwas.txt. Deshalb wurden sie damals umbenannt.

**Comment by RexDude** [comment]
Ich denke man muss hier den Ordner Prüfen statt die Datei. Um den Ordner gehts doch auch dass der da ist oder?
