### ISSUE TITLE
Install Addon - Autocheck files Ordner

### ISSUE THREAD

**Issue by Sysix** [redaxo/redaxo4#389]
Hallo Leute,

ich hab letztens seo42 auf die neuste Version aktualisiert und mir ist aufgefallen, dass der files/ Ordner nicht mitkopiert worden ist. So fehlten wichtige Skripte für's Backend.

Ist bei der Update-Funktion überhaupt eine Abfrage für den files/ Ordner eingebaut? 

@RexDude vielleicht ist hier in der UPDATE.md ein Hinweis zu setzen :) Bis es eine komfortable Lösung gibt

**Comment by RexDude** [comment]
Ich weise eigentlich in der Update.md drauf hin (siehe 4.0.0): "Addon-Files wurden geändert. Bitte Addon reinstallieren (NICHT deinstallieren und neu installieren!) und Browsercache löschen."

**Comment by Sysix-Coding** [comment]
Dann hab ich wieder das übersehen^^

**Comment by RexDude** [comment]
Wenn das REDAXO übernimmt muss aber vermutlich noch ein Hinweis raus das der Browsercache gelöscht werden muss.

**Comment by RexDude** [comment]
Wie waren deine Prüfungen?

Schau mal: http://www.redaxo.org/de/forum/post114793.html

**Comment by dergel** [comment]
das wird von REDAXO bewusst nicht gemacht .. Was beim UPDATE gemacht wird, entscheidet das AddOn .. (Update ist aber nur über den Installer möglich) .. Wenn Du Reinstall meinst, dann sollte das mit den files gehen.
