### ISSUE TITLE
bottom.php aufräumen.

### ISSUE THREAD

**Issue by dtpop** [redaxo/redaxo4#390]
Mein Vorschlag zu bottom.php: Zeile 27 ( < div id="rex-redaxo-link" >...< /div > ) entfernen.
Ich konnte in einem Addon die #rex-navi-page nicht verwenden, weil sich das #rex-redaxo-link Element per position:absolute darüber gelegt hat.
Lg Wolfgang

**Comment by tbaddade** [comment]
Dann müsste das AddOn die Positionierung anassen.

**Comment by dtpop** [comment]
Danke. Ich habe es mit display:none gelöst.
