### ISSUE TITLE
Image Manager: Falscher header bei JPEG?

### ISSUE THREAD

**Issue by skerbis** [redaxo/redaxo4#393]
Der Safari und auch Chrome haben Probleme mit dem Header image/jpg. 
Werden die Bilder mit diesem Header ausgeliefert, sorgt dies bei "in neuem Fenster oder Tab öffnen" dafür, dass diese als Downloads behandelt werden. 
Sendet man stattdessen image/jpeg ist alles ok.

**Comment by dergel** [comment]
hast du ein beispiel parat.. vielleicht auch einen link gerna auch per PM

**Comment by skerbis** [comment]
Hallo, 
schau mal hier: http://www.niag-online.de/143-0-NIAG-Logistik.html
Versuch mal mit dem Safari oder Chrome das Bild mit dem Zug im neuen Fenster zu öffnen

**Comment by tbaddade** [comment]
Kann ich bestätigen. In der Demo einfach mal die Url aufrufen

`/redaxo/index.php?rex_img_type=rex_mediapool_maximized&rex_img_file=main_teaser.jpg`

**Comment by dergel** [comment]
aber gerne nochmal prüfen.. auch ob die anderen jpg /pjpeg etc varianten gehen ..
