### ISSUE TITLE
Template Root Kategorie zuweisen

### ISSUE THREAD

**Issue by DanielWeitenauer** [redaxo/redaxo4#396]
Hi,

im Moment ist es nicht möglich, Templates der Root-Kategorie zuzuweisen. Sobald ich ein Template auch im Root benutzen möchte, muss ich es für alle Kategorien erlauben. Das ist unpraktisch wenn man z.B. System-Artikel oder ähnliches im Root anlegen möchte, die ein spezielles Template nutzen, das sonst nicht auf der Seite eingesetzt werden soll. Die Einschränkung müsste sich doch anpassen lassen, oder?

**Comment by tbaddade** [comment]
Ist aktuell nicht möglich. Verschiebe die Artikel in eine Offline-Kategorie. Mit einem rewriter könntest du Urls wiederum von /offlinekategorie/systemartikel.html auf /systemartikel.html legen.

Wäre jetzt die schnellere Lösung

**Comment by DanielWeitenauer** [comment]
Ich räume meine Issues auf und schließe hier, weil es inzwischen Version 5 gibt.
