### ISSUE TITLE
Falsches Templates beim Ändern des Artikelname

### ISSUE THREAD

**Issue by chrfickinger** [redaxo/redaxo4#400]
In der Strukturansicht werden inaktive Templates bei den Artikeln nicht angezeigt.
Klicke ich nun auf ändern, um den Artikelnamen zu editieren zeigt die Selectbox als Vorauswahl das Default-Template. Beim Speichern wird nun das neu ausgewählte Template benutzt, obwohl ich nur den Namen ändern will.

Vielleicht könnte man das inaktive Template in der Selectbox aufnehmen, wenn die Seite auf einem inaktiven Template basiert?

**Comment by chrfickinger** [comment]
Es wäre ausserdem sinnvoll, wenn man inaktive Templates in der Strukturansicht ebenfalls anzeigt (vielleicht in einer anderen Farbe). Schliesslich basiert die Seite ja auf dem Templates, auch wenn das Template inaktiv ist.

**Comment by RexDude** [comment]
> Vielleicht könnte man das inaktive Template in der Selectbox aufnehmen, wenn die Seite auf einem inaktiven Template basiert?

D.h. du hast ein inaktives Template bei nem Artikel eingestellt?
Wie hast du dass geschafft? Mit REDAXO Bordmittel geht das ja normal nicht.

> Es wäre ausserdem sinnvoll, wenn man inaktive Templates in der Strukturansicht ebenfalls anzeigt (vielleicht in einer anderen Farbe). Schliesslich basiert die Seite ja auf dem Templates, auch wenn das Template inaktiv ist.

Der Sinn uns Zweck inativer Templates ist ja eigentlich dass diese nicht als Auswahl zur verfügung stehen sondern halt nur von aktiven Templates eingebunden werden, sprich für den Programmierer da sind um sei Code besser zu strukturieren. Deshalb macht dir Forderung eigentlich keinen Sinn.

**Comment by chrfickinger** [comment]
Ich verstehe schon wie es vorgesehen ist. Inaktive Templates lassen sich allerdings auch hervorragend benutzen, um Seiten zu erstellen, an denen der Redakteur nichts mehr ändern soll (ausser halt den Artikelnamen).
D.h. ich habe ganz regulär mein Template produziert, die gewünschten Seiten damit angelegt und danach das Template abgeschaltet. Das funktioniert soweit prima, bis irgendwann der Artikelname geändert wird.

**Comment by RexDude** [comment]
Hmm ich finde da "missbrauchst" du aber etwas das Prinzip der aktiven/inaktiven Templates.
Wenn du dem Benutzer das Recht nehmen willst das Template zu ändern könnte man entweder ein neues Recht für Nicht-Admins einführen. Dieses würde aber dann wohl für alle Artikel gelten oder aber man könnte z.B. ein Plugin fürs Backend Utilities Addon schreiben wo man für einzelne Artikel angeben kann, dass die Template-Box entfernt wird etc. So wie beim hide_startarticle Plugin wo dem Nutzer der Staretartikel genommen wird :)

**Comment by chrfickinger** [comment]
Die Idee mit dem Plugin ist nicht schlecht, jedoch weiss ich nicht, ob sich der Aufwand dafür lohnt. Ansonsten muss ich halt schauen, ob ich es künftig irgendwie anders löse.

**Comment by tbaddade** [comment]
Das inaktive Templates nicht in der Auswahl auftauchen wird weiterhin so bleiben. Ich würde mir manchmal eher wünschen, dass manche aktiven Templates nur unter bestimmten Voraussetzungen auftauchen. 

@chrfickinger Für deinen Einsatz würde ich gar anders herangehen. MetaInfo. Hier definierst du welches Template geladen werden soll. In aktiven Template fragst du den MetaInfo Wert ab und lädst dann entsprechend das Template nach.

```php
<?php
if ($this->getValue('art_what') == 1) {
?>REX_TEMPLATE[2]<?php
} else {
?>REX_TEMPLATE[3]<?php
}
?>
```

**Comment by chrfickinger** [comment]
@tbaddade das ist auch ein guter Ansatz. Werd ich am Montag mal probieren :)

Schönes Wochenende und danke für die Tipps.
