### ISSUE TITLE
Mediendateinamen multiple underlines auf eins reduzieren

### ISSUE THREAD

**Issue by ghost** [redaxo/redaxo4#401]
Damit sowas zukünftig vemieden wird: baustahlgitter__cs_____cqs_____as_____aqs.pdf

**Comment by tbaddade** [comment]
Ich bin da zwiegespalten. Einerseits stört es mich auch, anderseits konnte ich so viel einfacher mal die Originaldatei auf dem Rechner wieder finden.

**Comment by staabm** [comment]
Wenn man die Dopplungen der _ reduziert wird man dadurch die Anzahl gleichnamiger Dateien die sich nur durch eine fortlaufende Zahl unterscheiden erhöhen. Diese Dateien sind, wie Thomas es bereits erwähnt, nicht mehr eindeutig aufs Original zurückzuführen, was manchmal ein Problem werden kann.

**Comment by RexDude** [comment]
Gut aber wie oft kommt es schon vor dass man die Originaldateien braucht, man hat sie ja im Mediepool. Dazu gekoppelt dann noch dass sie so umgeschrieben werden (ist ja auch selten).

Im Gegenzug dazu. In meinem Fall wird dieses PDF heruntergeladen und sieht halt seltsam aus dann beim Benutzer auf der Platte.
Auch SEO technisch macht jeweils nur ein Underline eine besser Figur.

**Comment by RexDude** [comment]
@staabm verstehe dein argument nicht ganz. bring doch mal ein bespiel wenns geht :)

**Comment by alexplusde** [comment]
wäre es nicht sowohl SEO-technisch besser, als auch benutzerfreundlicher, den ursprünglichen Dateinamen mitzuspeichern und auch anfordern zu können? Dem Nutzer kann es ja zunächst Mal egal sein, wie die Datei auf dem Server heißt, solange man einen schönen, URL-encodierten und eindeutigen Dateinamen anfordern kann.

**Comment by staabm** [comment]
Wie die Datei auf der Platte heißt und wie man es dem Browser zum download anbietet oder wie die keweilige Url ist sind 3 versch. Dinge. Wenn man es richtig machen will aus Seo/Usability Sicht darf man den technischen Dateinamen von der Platte nicht 1:1 durchreichen.

Beispiel:
Döner.jpg & Dööner.jpg 
Vorher: D_ner.jpg & D__ner.jpg
Nachher: D_ner.jpg & D_ner2.jpg

**Comment by tbaddade** [comment]
> Gut aber wie oft kommt es schon vor dass man die Originaldateien braucht, man hat sie ja im Mediepool.

Im Medienpool landen die, die für das Web optimiert wurden und nicht die Originaldatei.

> Im Gegenzug dazu. In meinem Fall wird dieses PDF heruntergeladen und sieht halt seltsam aus dann beim Benutzer auf der Platte.

Genau dann sollte man dem PDF einen eindeutigen Namen vergeben, so dass der Kunde dies auf seiner Platte auch zuordnen kann.

**Comment by staabm** [comment]
Alternativ um _ zu vermeiden. Ggf. Könnte man die Datei-umschreibefunktion schlauer machen sodass weniger _ entstehen, z.b. Wenn das Filesystem bestimmte Umlaute/Sonderzeichen im Dateinamen zulässt, diese nicht zu _ umschreiben.

**Comment by RexDude** [comment]
@staabm Umlaute werden mittkerweile nicht mehr in underlines verwandelt, dass war mal ;) Also dein Beispiel passt net.

@tbaddade

> Genau dann sollte man dem PDF einen eindeutigen Namen vergeben, so dass der Kunde dies auf seiner Platte auch zuordnen kann.

 naja, was willst du bitte denn bei 5 aufeinanderfolgenden underlines zuordnen.

Bitte lasst uns doch paar Beispiele durchgehen.

**Comment by staabm** [comment]
@RexDude wie heißt deine Datei  baustahlgitter__cs_____cqs_____as_____aqs.pdf im Original ?

**Comment by RexDude** [comment]
Original:
`Baustahlgitter ÖMAT CS – CQS – AS – AQS.pdf`

Umgeschrieben:
`baustahlgitter_oemat_cs_____cqs_____as_____aqs.pdf`

In diesem Fall wäre nur 1 underline kein Thema. Die Buchstaben und Zahlen bleiben ja erhalten, selbst wenn es eine weitere Datei gibt die dann genauso kdoiert wurde.

**Comment by staabm** [comment]
Neues Beispiel:

`Baustahlgitter ÖMAT CS – CQS – AS – AQS.pdf`
`Baustahlgitter ÖMAT CS –  CQS – AS – AQS.pdf` (Ein space mer zwischen Abkürzungen)

Es ist trivial Beispiele zu finden, die das gleiche Problem zeigen.

**Comment by tbaddade** [comment]
> naja, was willst du bitte denn bei 5 aufeinanderfolgenden underlines zuordnen.

Ich meine bevor ich eine Datei in den Medienpool lade und ich weiß das diese zum Download angeboten wird schreibe ich die Datei um.

Aus
Baustahlgitter ÖMAT CS – CQS – AS – AQS.pdf

Wird
oemat-baustahlgitter-cs-cqs-as-aqs.pdf

**Comment by RexDude** [comment]
Sowas kommt aber in real nicht vor. Wer bennent schon 2mal eine Datei gleich nur beim zweiten mal macht er merh Spaces rein. Und wenn:

"ohne"
baustahlgitter_oemat_cs_____cqs_____as_____aqs.pdf
baustahlgitter_oemat_cs______cqs______as______aqs.pdf

"mit"
 baustahlgitter_oemat_cs_cqs_as_aqs.pdf
 baustahlgitter_oemat_cs_cqs_as_aqs_1.pdf

zweite variante ist trotzdem eleganter und es bleiben alle chars erhalten!

**Comment by RexDude** [comment]
> Ich meine bevor ich eine Datei in den Medienpool lade und ich weiß das diese zum Download angeboten wird schreibe ich die Datei um.

Ja du vielleicht. Aber es gibt da drauss genügend Kunden und Redakteuer die das anscheiend nicht machen ;)

**Comment by tbaddade** [comment]
Müsste aus deiner Datei nicht eigentlich as werden:

baustahlgitter_oemat_cs_-_cqs_-_as_-_aqs.pdf
Bindestriche sind doch erlaubt

**Comment by RexDude** [comment]
Yo dacht ich auch. Aber hab die 2 grad aus der rex_file mir geholt. D.h. so wurds wohl umgeschrieben.

**Comment by tbaddade** [comment]
Dann sind das keine tatsächlichen Bindestriche. Wer krude Dateinamen vergibt, bekommt krude Dateinamen raus :)

**Comment by RexDude** [comment]
Stimmt sind keine normalen Bindestriche ;)
Ok dann neue Petition: unnormale Bindestriche als normale kodieren
Und mehrere Leerzeichen auf 1 reduzieren wäre auch schön.

DAUs müssen aber auch berücksichtigt werden Thomas.
Sind ja auch nur Nutzer ;)

**Comment by DanielWeitenauer** [comment]
Hi, wäre es nicht sinnvoll, EPs zur Verfügung zu stellen, um eine individuelle Transliteration zu ermöglichen? Wenn ich es richtig verstanden habe, werden bisher nur deutsche Sonderzeichen berücksichtigt. Würde ich ein kyrillisch benanntes Dokument hochladen, erhielte ich evtl. ein dokument, das _____________________.jpg heißt.

**Comment by RexDude** [comment]
@DanielWeitenauer :+1: 
Könnte man über SEO42 und das Sprachhandling gut übernehmen :)

**Comment by tbaddade** [comment]
@DanielWeitenauer Du könntest dich aktuell an diesen EP `MEDIA_ADDED` hängen. Du müsstest aber die Datei im Ordern `files` umbenennen und auch den Datenbankeintrag nachträglich anpassen.

**Comment by DanielWeitenauer** [comment]
@tbaddade Danke für den Tipp. Ich wollte jedoch nur ein Beispiel geben, bei dem es durchaus sinnvoll sein kann, die Radikalkur mit "_" noch etwas genauer zu dosieren. Sicherlich kann man so etwas im Notfall auch über Umwege lösen, aber aus meiner Sicht sind einfache und klare Möglichkeiten für so ein relevantes Thema wie die Internationalisierung auf Dauer notwendig. Ist der EP an der richtigen Stelle platziert könnte man dann evtl. auch den mehrfachen Unterstrichen begegnen.

**Comment by DanielWeitenauer** [comment]
Könnte man das Ganze nicht analog rex_getUrl/rex_parse_article_name regeln?
