### ISSUE TITLE
ctype-Spalte für Redakteur ausblenden

### ISSUE THREAD

**Issue by chrfickinger** [redaxo/redaxo4#402]
Ist es irgendwie möglich eine ctype-Spalte in Redaxo auszublenden und nur für einen Admin sichtbar zu machen?

**Comment by tbaddade** [comment]
Ja. Hänge dich an diesen EP `PAGE_CONTENT_CTYPE_MENU`und schmeiße den Ctype aus dem Array raus.

**Comment by chrfickinger** [comment]
danke.
