### ISSUE TITLE
Module werden vor Template geladen?

### ISSUE THREAD

**Issue by tzfrs** [redaxo/redaxo4#404]
Hi,

ich habe folgendes Problem. In einem Template moechte ich gewisse Variablen definieren. Das Template nenne ich Bootstrap. Wenn ich dort folgendes mache

`$REX['Foo'] = Bar::find(rex_request('foo', 'int', null);`

und es spaeter im Modul aufrufen will

`var_dump($REX['Foo']);`

dann bekome ich den Fehler, das Foo nicht definiert ist. 

>Notice: Undefined index: Foo in /var/www/htdocs/redaxo/include/classes/class.rex_article.inc.php(126) : eval()'d code on line 28

Wenn ich es aber umgekehrt mache, also im Modul die Variable definiere und im Template dann die Variable versuche auszugeben, dann klappt es.

Ich benutze REDAXO: 4.6.1. Das komische ist, dass ich dasselbe in einem alten Projekt mache und es dort problemlos funktioniert, wieso geht es hier nicht?

**Comment by gharlan** [comment]
Die Zeile steht im Template ganz oben? Es gibt also garantiert nicht schon vorher einen Aufruf von `REX_ARTICLE[]` oder `$this->getArticle()` oder ähnliches?

In dem Bereich hat sich im Core jedenfalls eigentlich nichts verändert, es liegt also wahrscheinlich am Templatecode.

**Comment by tzfrs** [comment]
Ja, die steht ganz oben. Das Template hat die ID 9 und wird bei allen Templates ganz oben eingefügt über 

`REX_TEMPLATE[9]`. Wenn ich normale Ausgaben mache, dann klappt das auch problemlos, da wird das Template auch "vorher" genommen, aber es scheint, dass irgendwie die Module vor den Templates 
`evaluated` werden.

Das mit dem Core glaub ich halt auch nicht, weil ich ein anderes Projekt habe, dass es genau so macht, und dort es problemlos funktioniert. In meinem Template-Code steht auch wirklich nur diese eine Zeile, die ich da oben geschrieben habe.

**Comment by tzfrs** [comment]
Hier ist mein kompletter Template-Code

    <?php
    $REX['Foo'] = 'YES';
    ?>


Und hier der vom Modul

    <?php
    var_dump($REX['Foo']);
    ?>

Und dann kommt der besagte Fehler

**Comment by tzfrs** [comment]
Kann es eventuell daran liegen, dass das Template dass das Bootstrap einbindet eine niedrigere ID hat? Also das Bootstrap hat die ID 9, und die anderen Templates haben 1-8?

**Comment by tzfrs** [comment]
Ich habe gerade ein neues Template erstellt, ID 10. Dort Das Template mit der ID9 eingebunden, und zack, es funktioniert problemlos. Kann dies wirklich der Grund dafür sein?

**Comment by tzfrs** [comment]
Hey, du hattest Recht. Es lag wirklich an mir. Ich hab in einem der Untertemplates den Teil auskommentiert der das Template laedt, danach auf `$this->getArticle()` zugegriffen und dann wieder unkommentiert das Template eingebunden. Klassischer Fall von "Problem exists between keyboard and computer"

**Comment by gharlan** [comment]
Ok, ansonsten wäre es auch recht mysteriös gewesen ;)

**Comment by tzfrs** [comment]
Was denkst du, wie ich mich gefühlt habe, es hat ja in anderen Projekten problemlos funktioniert. :D
