### ISSUE TITLE
Deprecates + Notices fixen

### ISSUE THREAD

**Issue by RexDude** [redaxo/redaxo4#414]
Besteht noch die Möglichkeit einen PR zu schicken um die Sachen zu fixen?

**Comment by gharlan** [comment]
Ich sag es mal so: Wenn alles eindeutig kompatibel bleibt, und dafür keine zu großen Verrenkungen notwendig sind, dann können wir das schon noch aufnehmen.
Also vielleicht besser vorher mal andeuten, was das jeweils für Änderungen wären, bevor du alles machst.

**Comment by RexDude** [comment]
Ja hat ich eh vor :D

**Comment by RexDude** [comment]
Mein Ansatz wäre der hier (Beispiel rex_sql Konstruktor)

```php
    // this is the new style constructor used by newer php versions.
    // important: if you change the signatur of this method, change also the signature of rex_sql()
    function __construct($DBID = 1) { 
        $this->rex_sql($DBID);
    }

    // this is the deprecated old style constructor kept for compat reasons. 
    // important: if you change the signatur of this method, change also the signature of __construct()
    /*private*/ function rex_sql($DBID = 1)
    {
        global $REX;

        $this->debugsql = false;
        $this->selectDB($DBID);

        $this->flush();
    }
```

**Comment by gharlan** [comment]
Ich denke, das passt.
Am besten den `/*private*/`-Kommentar beim neuen Konstruktor auch davor setzen, aber auch nur als Kommentar.

**Comment by RexDude** [comment]
Ja stimmt der fehlt der vollständigkeitd halber.
Mit der Lösung sollt alles kompatibel leiben und gleichzeitig sollten die meisten Meldungen verschwinden. Extra Notices würd ich aber euch überlassen und diese dann nur melden.

**Comment by gharlan** [comment]
Ok, alles klar. Ich warte dann noch den PR ab, und werde dann die 4.7.2 fertig machen (wegen des Datenbank-Namens-Problem).

Kannst gerne Notices melden, von uns wird aber keiner welche entfernen.

**Comment by RexDude** [comment]
Ich kann sie auch fixen aber schaut dann bitte gut drüber weil ich steck im code ja nicht so drin wie ihr :)
PR kommt die Tage...

**Comment by RexDude** [comment]
Ok 3 PR's für Konstruktor Fixes gesendet.

Mir ist jetzt noch was aufgefallen:

Habe ich dass hier in der master.inc.php:
`error_reporting(error_reporting() & ~E_STRICT & ~E_DEPRECATED);`

...bekomme ich trotzdem bei einer frischen Install ein: `Notice: Only variables should be passed by reference in /home/dude/Projekte/Web/Redaxo4/htdocs/redaxo/include/classes/class.rex_form.inc.php on line 435` ..und zwar wenn ich einfach das art_online_from Meta Info öffne zum editieren.

Habe ich dass hier in der master.inc.php:
`error_reporting(0);`

...kommt an genannter Stelle die notice nicht mehr.
Komisch irgendwie oder?

PHP 7.0.8 unter Linux Mint.

**Comment by gharlan** [comment]
Es werden ja nur E_STRICT und E_DEPRECATED deaktiviert, aber keine E_NOTICE.
Muss ich mal schauen, ob ich die Notice auch bekomme.

**Comment by RexDude** [comment]
So wärs richtiger denk ich:
`error_reporting(error_reporting() & ~E_NOTICE & ~E_DEPRECATED);`

oder so:
`error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED | E_STRICT);`

**Comment by RexDude** [comment]
php.ini beispiele:

```
; Common Values:
;   E_ALL & ~E_NOTICE  (Show all errors, except for notices and coding standards warnings.)
;   E_ALL & ~E_NOTICE | E_STRICT  (Show all errors, except for notices)
;   E_COMPILE_ERROR|E_RECOVERABLE_ERROR|E_ERROR|E_CORE_ERROR  (Show only errors)
;   E_ALL | E_STRICT  (Show all errors, warnings and notices including coding standards.)
```

**Comment by gharlan** [comment]
Wichtig ist, mit `error_reporting()` zu arbeiten, nicht `E_ALL`. Falls jemand schon in der php.ini mehr deaktiviert hat, sollte R4 die nicht wieder aktivieren.

Wenn dann also eher:
`error_reporting(error_reporting() & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED);`

Falls wir denn die Notices wirklich deaktivieren müssen. Muss ich mal schauen.

**Comment by RexDude** [comment]
achso. ich dachte dass auch die notices hier weg sollen. ja dann erfüllts so natürlich seinen zweck. aber man könnte ja drüber nachdenken die evtl. auch auszublenden....oder halt fixen ;)

**Comment by RexDude** [comment]
auf nem live server sollten sie ja eh aus sein...dann ists vielleicht egal.

**Comment by gharlan** [comment]
Nochmal drüber nachgedacht. Seit PHP 7 gibt es ja eigentlich E_STRICT nicht mehr, und manche der Meldungen sind nun zu E_NOTICEs geworden, andere zu E_DEPRECATED.
Daher füge ich E_NOTICE noch hinzu, also dass die auch immer unterdrückt werden.

**Comment by RexDude** [comment]
ok klingt gut.
