### ISSUE TITLE
Fehler: Installation Schritt 4, php 7.1.4

### ISSUE THREAD

**Issue by Goldfischpeter** [redaxo/redaxo4#417]
Bei Installation, Schritt 3 (Setup Database) lädt die folgende Seite nicht vollständig. 
Abbruch der Installation. Die Ausgabe endet im HTML hier:

```
<div id="rex-wrapper">
<div id="rex-wrapper2">
```

**Comment by staabm** [comment]
Irgendwelche errors im system log?

**Comment by Goldfischpeter** [comment]
Hab leider keinen Zugriff auf die Logs. Es hängt in der Funktion rex_setup_setDBcharset(). Es gibt hier keinen Fehler noch wir im Debug-Modus etwas ausgegeben.

**Comment by gharlan** [comment]
Du könntest diesen Bereich einfach mal auskommentieren, und schauen, ob dann das Setup durchgeht:
https://github.com/redaxo/redaxo4/blob/fbdff225792ce38f5e34f42eaf9f8c4c42b57ec9/redaxo/include/pages/setup.inc.php#L168-L175

**Comment by Goldfischpeter** [comment]
Es bleibt danach in der nächsten Funktion  rex_setup_import() hängen. 
Hier in beim Aufruf von rex_a1_import_db($import_sql);
Der Parameter $import_sql ist gesetzt "redaxo/include/install/redaxo4_7.sql"

**Comment by Goldfischpeter** [comment]
rex_a1_import_db() -> zeile 127: $sql = rex_sql::factory(); -> class.rex_sql.inc.php -> rex_sql() -> selectDB() -> if (!@mysql_select_db($REX['DB'][$DBID]['NAME'], $this->identifier))

hab mysql_select_db mit mysqli_connect ersetzt

danach hängt es $this->setQuery('SET SQL_MODE=""');

**Comment by gharlan** [comment]
Ich habe es mir angeschaut: Der eigentliche Fehler ist, dass wenn das DB-Passwort ein `$` enthält, das Passwort falsch escaped in die master.inc.php geschrieben wird.
Aus `foo$bar` wird `'foo\$bar'`, da es in einfachen Anführungszeichen gesetzt wird, ist das Escaping aber falsch.
