### ISSUE TITLE
Fatal error - beim parsen via replaceLinks Methode

### ISSUE THREAD

**Issue by tbaddade** [redaxo/redaxo4#432]
|| Version|
|---|---|
| REDAXO | 4.7.3 |
| PHP | 5.6.34 |
| MySQL | 5.6.19 |

```
Fatal error: Using $this when not in object context in /redaxo/include/classes/class.rex_article_base.inc.php on line 528
```

Wäre hier
https://github.com/redaxo/redaxo4/blob/master/redaxo/include/classes/class.rex_article_base.inc.php#L528

Der Fehler kommt u.a. wenn man diesen Text eingibt.

```
Blinder Text ist kein Blindtext.

"Details":redaxo://15
```

Auslöser ist der Link via Textilemarkup.

**Comment by tbaddade** [comment]
StackTrace

```
#0 [internal function]: {closure}(Array)
#1 /../classes/class.rex_article_base.inc.php(534): preg_replace_callback('@redaxo://(\d+)...', Object(Closure), '...')
#2 /../classes/class.rex_article_base.inc.php(409): rex_article_base->replaceLinks('...')
#3 index.php(55): rex_article_base->getArticleTemplate()
#4 {main}
```

**Comment by tbaddade** [comment]
Fehler gefunden

Das Frontend läuft unter `PHP 5.3.x` und nicht wie das Backend unter `5.6.x`.

D.h. um unsere [REX_MIN_PHP_VERSION](https://github.com/redaxo/redaxo4/blob/master/redaxo/include/master.inc.php#L9) zu unterstützen müsste die Methode angepasst werden.

**Comment by staabm** [comment]
Super infos zusammengesammelt. Da bleiben keine wünsche offen :)

**Comment by tbaddade** [comment]
> Super infos zusammengesammelt.

Danke. Es soll nicht unerwähnt bleiben, dass auch @gharlan seinen Anteil daran hatte.
